import type { Hypothesis } from "@/types/discovery";

const CONFIDENCE_STYLE: Record<Hypothesis["confidence"], string> = {
  high: "text-emerald-400 border-emerald-400/30 bg-emerald-400/10",
  medium: "text-amber border-amber/30 bg-amber-soft",
  low: "text-muted border-border bg-surface-raised",
};

export function HypothesisList({ hypotheses }: { hypotheses: Hypothesis[] }) {
  return (
    <section className="rounded-xl border border-border bg-surface p-5">
      <div className="flex flex-wrap items-end justify-between gap-2">
        <h2 className="text-xs font-semibold tracking-[0.15em] text-muted uppercase">
          Generated hypotheses
        </h2>
        <p className="text-sm text-muted">{hypotheses.length} hypothesis(es)</p>
      </div>
      <p className="mt-2 text-sm text-muted">
        Hypotheses are AI-generated interpretations of the strongest opportunities.
        They are not validated findings until checked against primary research.
      </p>

      {hypotheses.length === 0 ? (
        <p className="mt-4 rounded-md border border-border bg-surface-raised px-3 py-6 text-center text-sm text-muted">
          No hypotheses yet. They are generated from the top-ranked opportunities
          once evidence has been extracted.
        </p>
      ) : (
        <ul className="mt-4 space-y-3">
          {hypotheses.map((hypothesis) => (
            <li
              key={hypothesis.id}
              className="rounded-lg border border-border bg-surface-raised p-4"
            >
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div>
                  <p className="text-xs text-muted">{hypothesis.theme}</p>
                  <h3 className="mt-1 text-sm font-semibold text-foreground">
                    {hypothesis.hypothesis}
                  </h3>
                </div>
                <span
                  className={`shrink-0 rounded-full border px-2 py-0.5 text-xs font-medium capitalize ${CONFIDENCE_STYLE[hypothesis.confidence]}`}
                >
                  {hypothesis.confidence} confidence
                </span>
              </div>

              <dl className="mt-3 grid gap-3 text-xs sm:grid-cols-2">
                <div>
                  <dt className="font-medium text-foreground/80">Target behaviour</dt>
                  <dd className="mt-0.5 text-muted">{hypothesis.targetBehaviour}</dd>
                </div>
                <div>
                  <dt className="font-medium text-foreground/80">Suspected root cause</dt>
                  <dd className="mt-0.5 text-muted">{hypothesis.suspectedRootCause}</dd>
                </div>
                <div>
                  <dt className="font-medium text-foreground/80">Evidence supporting</dt>
                  <dd className="mt-0.5 text-muted">
                    {hypothesis.evidenceSupporting.length > 0
                      ? hypothesis.evidenceSupporting.map((item, index) => (
                          <span key={index} className="block">
                            “{item}”
                          </span>
                        ))
                      : "—"}
                  </dd>
                </div>
                <div>
                  <dt className="font-medium text-foreground/80">Evidence that weakens it</dt>
                  <dd className="mt-0.5 text-muted">
                    {hypothesis.evidenceWeakening.length > 0
                      ? hypothesis.evidenceWeakening.join(" ")
                      : "—"}
                  </dd>
                </div>
                <div>
                  <dt className="font-medium text-foreground/80">Would validate it</dt>
                  <dd className="mt-0.5 text-muted">{hypothesis.validation}</dd>
                </div>
                <div>
                  <dt className="font-medium text-foreground/80">Would falsify it</dt>
                  <dd className="mt-0.5 text-muted">{hypothesis.falsification}</dd>
                </div>
                <div>
                  <dt className="font-medium text-foreground/80">Potential intervention</dt>
                  <dd className="mt-0.5 text-muted">{hypothesis.productIntervention}</dd>
                </div>
                <div>
                  <dt className="font-medium text-foreground/80">Expected value</dt>
                  <dd className="mt-0.5 text-muted">
                    User: {hypothesis.expectedUserValue} Business:{" "}
                    {hypothesis.expectedBusinessValue}
                  </dd>
                </div>
              </dl>

              <p className="mt-3 border-t border-border pt-2 text-xs text-muted">
                {hypothesis.source === "ai_generated"
                  ? "Generated by the configured AI provider from grounded opportunity evidence."
                  : "Generated from opportunity statistics only (no AI provider was configured for this run)."}
                {hypothesis.isMock ? " MOCK/DEMO — not research evidence." : ""}
              </p>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}
